@startuml container_diagram_existing_data_processing
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' Elements
Enterprise_Boundary(System, "[Container] Existing Process: Testing Pipeline (Data Processing)") {
    Enterprise_Boundary(CloudSystem, "External Network") {    
        
        Enterprise_Boundary(FacilitySystem, "Test Facility") {
            Person(Tester2, "Test Engineer 2")

            Container_Ext(FileStorage, "File Storage", "nfs", "Storage location for unprocessed test data")
            Container(DataAnalysis, "Data Analysis", "matlab", "Perform target extraction and analysis")
        }
    }
}

' Relationships
Rel(Tester2, DataAnalysis, "initiates  data  analysis")
BiRel(DataAnalysis, FileStorage, "uses  unprocessed  data")
Rel(DataAnalysis, Tester2, "analysis  results:", ".csv")

@enduml

