@startuml container_diagram_proposal_data_collection
!include colors.plantuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Proposal: Testing Automation Pipeline (Data Collection)
LAYOUT_WITH_LEGEND()

AddRelTag("purple_rel", $textColor="MediumPurple", $lineColor="MediumPurple")
AddRelTag("golden_rel", $textColor="#B8860B", $lineColor="#B8860B")
AddRelTag("coral_rel", $textColor="Coral", $lineColor="Coral")

' Elements

Boundary(CloudNetwork, "External Network") <<boundary_solid_red>> {        
    Container_Ext(Jira, "Issue Tracking", "Jira", "Test engineer task tracking.")
    
    Boundary(FacilitySystem, "Test Facility") <<boundary_solid_blue>> {
        Person(Tester1, "Test Engineer 1")
        Container_Ext(Lidar, "Lidar", "Iris", "Sensor under test.")
        
        Boundary(TestWorkStation, "Test Workstation") <<boundary_solid_gray>> {
            Container(Valkyrie, "Labview", "Valkyrie", "GUI for lidar testing.")
            Container_Ext(PcapConverter, "Pcap Converter", "Python", "Converts .pcap files to .csv.")
            Container_Ext(TargetExtraction, "Target Extraction", "Python", "Extracts targets from point cloud data.")
            Container_Ext(Wireshark, "Wireshark CLI", ".pcap", "Records point cloud data and writes .pcap files.")
            Container_Ext(FileSystem, "File System", "Local Storage", "Storage location for unprocessed .pcap files.")
            ContainerDb(Database, "Database", "SurrealDB", "Storage backend for diagnostics data and extraction results.")
            Container(WebServer, "Web Server", "Rust Rocket.rs", "REST API.")
        }
    }
}

'Lay_L(Tester1, Jira)

' Relationships
Rel(Tester1, Valkyrie, "(1) trigger  lidar  test", "gui", $tags="coral_rel")
BiRel(Jira, Valkyrie, "(1) work  item", "rest  api", $tags="coral_rel")

Rel(Valkyrie, Lidar, "(2) request  diagnostics  data", "doip")
Rel(Lidar, Valkyrie, "(3) received  diagnostics  data", "doip", $tags="golden_rel")
Rel(Lidar, Wireshark, "(3) publish  point  cloud", "udp", $tags="golden_rel")
Rel(Wireshark, FileSystem, "(4) write  point  cloud  files", ".pcap", $tags="purple_rel")
Rel(Valkyrie, WebServer, "(4) send  diagnostics  results", "http", $tags="purple_rel")
Rel(Valkyrie, WebServer, "(7) send  target  extraction  results", "http")
BiRel(Valkyrie, PcapConverter, "(5) triggers", "exe")
BiRel(Valkyrie, TargetExtraction, "(6) triggers", "exe")
Rel(WebServer, Database, "write  data", "sql")

@enduml

