@startuml architecture_colors

skinparam package<<boundary_solid_red>> {
  BorderColor FireBrick 
  LineType solid
}

skinparam package<<boundary_solid_green>> {
  BorderColor ForestGreen 
  LineType solid
}

skinparam package<<boundary_solid_blue>> {
  BorderColor RoyalBlue
  LineType solid
}

skinparam package<<boundary_solid_gray>> {
  BorderColor DimGray
  LineType solid
}


@enduml