@startuml container_diagram_existing_data_collection
!include colors.plantuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Existing Process: Testing Pipeline (Data Collection)
LAYOUT_WITH_LEGEND()

' Elements
Boundary(CloudNetwork, "External Network") <<boundary_solid_red>> {    
    
    Boundary(LuminarNetwork, "Luminar Network") <<boundary_solid_green>> {    
        Container_Ext(Jira, "Issue Tracking", "Jira")
        Container_Ext(FileStorage, "File Storage", "nfs", "Storage location for unprocessed test data.")
        
        Boundary(FacilitySystem, "Test Facility") <<boundary_solid_blue>> {
            Person(Tester1, "Test Engineer 1")
            Container_Ext(TestWorkStation, "Workstation", "Windows, Labview (Valkyrie)", "Computer running lidar testing software.")
            Container_Ext(Lidar, "Lidar", "Iris, Iris+")
        }
    }
}

' Relationships
Rel(Tester1, TestWorkStation, "(2) trigger  lidar  test", "gui")
Rel(Tester1, Jira, "(1) uses", "gui")
Rel(TestWorkStation, FileStorage, "(5) write  test  files", ".pcap, .csv, .txt")
Rel(TestWorkStation, Lidar, "(3) sensor  commands", "telnet, someip")
Rel(Lidar, TestWorkStation, "(4) point  cloud,\ndiagnostics  data", "udp, telnet, someip")

@enduml

