@startuml system_context_diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Testing Automation Pipeline

LAYOUT_WITH_LEGEND()
LAYOUT_TOP_DOWN()

' Elements
Person_Ext(Tester, "Test Engineer 1")
System(DataCollection, "Data Collection", "Capture and store sensor test data.")
System(DataProcessor, "Data Transfer", "Transfer data from local test workstations to the cloud.")
System(DataView, "Data Visualization", "Visualize test data.")
Person_Ext(DataAnalyst, "Test Engineer 2")

' Relationships
Rel_Neighbor(Tester, DataCollection, "(1) initiates  test")
Rel(DataCollection, DataProcessor, "(2) causes")
Rel(DataProcessor, DataView, "(3) make  data  available")
Rel_Neighbor(DataView, DataAnalyst, "(4) test  results")

@enduml

